import AddUserComponents from "@/components/AddUserComponents";
import ServerProtectedComponent from "@/components/ServerProtectedComponents";
import UpdateUserComponents from "@/components/UpdateUserComponents";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Update User",
  description: "Generated by create next app",
};

export default function updateUser() {
  return (
    <ServerProtectedComponent>
      <UpdateUserComponents />
    </ServerProtectedComponent>
  );
}
