import AddUserComponents from "@/components/AddUserComponents";
import ServerProtectedComponent from "@/components/ServerProtectedComponents";
import UpdateUserComponents from "@/components/UpdateUserComponents";
import ViewUserDetailComponents from "@/components/ViewUserDetailComponents";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "User Detail",
  description: "Generated by create next app",
};

export default function viewUser() {
  return (
    <ServerProtectedComponent>
      <ViewUserDetailComponents />
    </ServerProtectedComponent>
  );
}
