import AddUserComponents from "@/components/AddUserComponents";
import ServerProtectedComponent from "@/components/ServerProtectedComponents";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Add User",
  description: "Generated by create next app",
};

export default function addUser() {
  return (
    <ServerProtectedComponent>
      <AddUserComponents />
    </ServerProtectedComponent>
  );
}
