import DashboardComponents from "@/components/DashboardComponents";
import ServerProtectedComponent from "@/components/ServerProtectedComponents";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "iProc",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <ServerProtectedComponent>
      <DashboardComponents />
    </ServerProtectedComponent>
  );
}
